#!/usr/bin/env python3
"""
美股个股清单 - 自维护版本
格式: ("代码", "公司名", "板块")
板块与ETF趋势系统完全一致，确保两个系统联动准确
"""

STOCKS_US = [
    # ── 半导体 ────────────────────────────────────────────────────────────
    ("NVDA",  "NVIDIA",                       "半导体"),
    ("AMD",   "Advanced Micro Devices",       "半导体"),
    ("AVGO",  "Broadcom",                     "半导体"),
    ("QCOM",  "Qualcomm",                     "半导体"),
    ("TXN",   "Texas Instruments",            "半导体"),
    ("AMAT",  "Applied Materials",            "半导体"),
    ("LRCX",  "Lam Research",                 "半导体"),
    ("KLAC",  "KLA Corp",                     "半导体"),
    ("MRVL",  "Marvell Technology",           "半导体"),
    ("INTC",  "Intel",                        "半导体"),
    ("ON",    "ON Semiconductor",             "半导体"),
    ("MPWR",  "Monolithic Power Systems",     "半导体"),
    ("TER",   "Teradyne",                     "半导体"),
    ("KEYS",  "Keysight Technologies",        "半导体"),
    ("NXPI",  "NXP Semiconductors",           "半导体"),
    ("MCHP",  "Microchip Technology",         "半导体"),
    ("MU",    "Micron Technology",            "半导体"),
    ("GFS",   "GlobalFoundries",              "半导体"),
    ("SMCI",  "Super Micro Computer",         "半导体"),
    ("ARM",   "ARM Holdings",                 "半导体"),
    ("WOLF",  "Wolfspeed",                    "半导体"),
    ("ACLS",  "Axcelis Technologies",         "半导体"),
    ("ONTO",  "Onto Innovation",              "半导体"),
    ("OLED",  "Universal Display",            "半导体"),
    ("MKSI",  "MKS Instruments",              "半导体"),
    ("FORM",  "FormFactor",                   "半导体"),
    ("COHU",  "Cohu",                         "半导体"),
    ("VICR",  "Vicor",                        "半导体"),
    ("AEIS",  "Advanced Energy",              "半导体"),
    ("LSCC",  "Lattice Semiconductor",        "半导体"),
    ("UCTT",  "Ultra Clean Holdings",         "半导体"),
    ("POWI",  "Power Integrations",           "半导体"),
    ("SLAB",  "Silicon Laboratories",         "半导体"),
    ("SMTC",  "Semtech",                      "半导体"),
    ("SITM",  "SiTime",                       "半导体"),
    ("AMBA",  "Ambarella",                    "半导体"),
    ("ASML",  "ASML Holding",                 "半导体"),
    ("ADI",   "Analog Devices",               "半导体"),
    ("TEL",   "TE Connectivity",              "半导体"),
    ("APH",   "Amphenol",                     "半导体"),
    ("GLW",   "Corning",                      "半导体"),
    ("STX",   "Seagate Technology",           "半导体"),
    ("WDC",   "Western Digital",              "半导体"),

    # ── 科技 ──────────────────────────────────────────────────────────────
    ("AAPL",  "Apple",                        "科技"),
    ("MSFT",  "Microsoft",                    "科技"),
    ("ORCL",  "Oracle",                       "科技"),
    ("CRM",   "Salesforce",                   "科技"),
    ("ACN",   "Accenture",                    "科技"),
    ("CSCO",  "Cisco",                        "科技"),
    ("IBM",   "IBM",                          "科技"),
    ("NOW",   "ServiceNow",                   "科技"),
    ("INTU",  "Intuit",                       "科技"),
    ("ADSK",  "Autodesk",                     "科技"),
    ("ANSS",  "ANSYS",                        "科技"),
    ("CDNS",  "Cadence Design Systems",       "科技"),
    ("SNPS",  "Synopsys",                     "科技"),
    ("MSI",   "Motorola Solutions",           "科技"),
    ("HPQ",   "HP Inc",                       "科技"),
    ("HPE",   "Hewlett Packard Enterprise",   "科技"),
    ("DELL",  "Dell Technologies",            "科技"),
    ("NTAP",  "NetApp",                       "科技"),
    ("STX",   "Seagate Technology",           "科技"),
    ("ZBRA",  "Zebra Technologies",           "科技"),
    ("CTSH",  "Cognizant Technology",         "科技"),
    ("IT",    "Gartner",                      "科技"),
    ("CDW",   "CDW Corp",                     "科技"),
    ("GDDY",  "GoDaddy",                      "科技"),
    ("GEN",   "Gen Digital",                  "科技"),
    ("AKAM",  "Akamai Technologies",          "科技"),
    ("EPAM",  "EPAM Systems",                 "科技"),
    ("PTC",   "PTC Inc",                      "科技"),
    ("FFIV",  "F5 Inc",                       "科技"),

    # ── 人工智能 ──────────────────────────────────────────────────────────
    ("GOOGL", "Alphabet Class A",             "人工智能"),
    ("GOOG",  "Alphabet Class C",             "人工智能"),
    ("META",  "Meta Platforms",               "人工智能"),
    ("PLTR",  "Palantir",                     "人工智能"),
    ("IONQ",  "IonQ",                         "人工智能"),
    ("RXRX",  "Recursion Pharma",             "人工智能"),

    # ── 云计算软件 ────────────────────────────────────────────────────────
    ("DDOG",  "Datadog",                      "云计算软件"),
    ("SNOW",  "Snowflake",                    "云计算软件"),
    ("ZS",    "Zscaler",                      "云计算软件"),
    ("TEAM",  "Atlassian",                    "云计算软件"),
    ("WDAY",  "Workday",                      "云计算软件"),
    ("OKTA",  "Okta",                         "云计算软件"),
    ("NTNX",  "Nutanix",                      "云计算软件"),
    ("CFLT",  "Confluent",                    "云计算软件"),
    ("GTLB",  "GitLab",                       "云计算软件"),
    ("PATH",  "UiPath",                       "云计算软件"),
    ("RELY",  "Remitly Global",               "云计算软件"),
    ("FIVN",  "Five9",                        "云计算软件"),
    ("ATEN",  "A10 Networks",                 "云计算软件"),
    ("BAND",  "Bandwidth",                    "云计算软件"),
    ("NTCT",  "NetScout Systems",             "云计算软件"),
    ("PAYC",  "Paycom Software",              "云计算软件"),

    # ── 网络安全 ──────────────────────────────────────────────────────────
    ("CRWD",  "CrowdStrike",                  "网络安全"),
    ("PANW",  "Palo Alto Networks",           "网络安全"),
    ("FTNT",  "Fortinet",                     "网络安全"),

    # ── 金融 ──────────────────────────────────────────────────────────────
    ("BRK-B", "Berkshire Hathaway",           "金融"),
    ("JPM",   "JPMorgan Chase",               "金融"),
    ("BAC",   "Bank of America",              "金融"),
    ("WFC",   "Wells Fargo",                  "金融"),
    ("GS",    "Goldman Sachs",                "金融"),
    ("MS",    "Morgan Stanley",               "金融"),
    ("C",     "Citigroup",                    "金融"),
    ("BLK",   "BlackRock",                    "金融"),
    ("SCHW",  "Charles Schwab",               "金融"),
    ("AXP",   "American Express",             "金融"),
    ("CB",    "Chubb",                        "金融"),
    ("MMC",   "Marsh & McLennan",             "金融"),
    ("PGR",   "Progressive",                  "金融"),
    ("MET",   "MetLife",                      "金融"),
    ("PRU",   "Prudential Financial",         "金融"),
    ("AFL",   "Aflac",                        "金融"),
    ("TRV",   "Travelers Companies",          "金融"),
    ("AON",   "Aon",                          "金融"),
    ("ICE",   "Intercontinental Exchange",    "金融"),
    ("CME",   "CME Group",                    "金融"),
    ("SPGI",  "S&P Global",                   "金融"),
    ("MCO",   "Moody's",                      "金融"),
    ("USB",   "US Bancorp",                   "金融"),
    ("PNC",   "PNC Financial",                "金融"),
    ("TFC",   "Truist Financial",             "金融"),
    ("COF",   "Capital One",                  "金融"),
    ("DFS",   "Discover Financial",           "金融"),
    ("SYF",   "Synchrony Financial",          "金融"),
    ("FITB",  "Fifth Third Bancorp",          "金融"),
    ("RF",    "Regions Financial",            "金融"),
    ("V",     "Visa",                         "金融"),
    ("MA",    "Mastercard",                   "金融"),
    ("PYPL",  "PayPal",                       "金融"),
    ("FI",    "Fiserv",                       "金融"),
    ("FIS",   "Fidelity National Info",       "金融"),
    ("GPN",   "Global Payments",              "金融"),
    ("COIN",  "Coinbase",                     "金融"),
    ("MSCI",  "MSCI Inc",                     "金融"),
    ("FDS",   "FactSet Research",             "金融"),
    ("LPLA",  "LPL Financial",                "金融"),
    ("COOP",  "Mr. Cooper Group",             "金融"),
    ("UWMC",  "UWM Holdings",                 "金融"),
    ("OPEN",  "Opendoor Technologies",        "金融"),
    ("ENVA",  "Enova International",          "金融"),
    ("FCNCA", "First Citizens BancShares",    "金融"),

    # ── 医药医疗 ──────────────────────────────────────────────────────────
    ("LLY",   "Eli Lilly",                    "医疗医药"),
    ("UNH",   "UnitedHealth Group",           "医疗医药"),
    ("JNJ",   "Johnson & Johnson",            "医疗医药"),
    ("ABBV",  "AbbVie",                       "医疗医药"),
    ("MRK",   "Merck",                        "医疗医药"),
    ("PFE",   "Pfizer",                       "医疗医药"),
    ("TMO",   "Thermo Fisher Scientific",     "医疗医药"),
    ("ABT",   "Abbott Laboratories",          "医疗医药"),
    ("DHR",   "Danaher",                      "医疗医药"),
    ("BMY",   "Bristol-Myers Squibb",         "医疗医药"),
    ("AMGN",  "Amgen",                        "医疗医药"),
    ("GILD",  "Gilead Sciences",              "医疗医药"),
    ("REGN",  "Regeneron Pharmaceuticals",    "医疗医药"),
    ("VRTX",  "Vertex Pharmaceuticals",       "医疗医药"),
    ("BIIB",  "Biogen",                       "医疗医药"),
    ("MRNA",  "Moderna",                      "医疗医药"),
    ("ISRG",  "Intuitive Surgical",           "医疗医药"),
    ("SYK",   "Stryker",                      "医疗医药"),
    ("BSX",   "Boston Scientific",            "医疗医药"),
    ("MDT",   "Medtronic",                    "医疗医药"),
    ("EW",    "Edwards Lifesciences",         "医疗医药"),
    ("BDX",   "Becton Dickinson",             "医疗医药"),
    ("HUM",   "Humana",                       "医疗医药"),
    ("CI",    "Cigna",                        "医疗医药"),
    ("CNC",   "Centene",                      "医疗医药"),
    ("MCK",   "McKesson",                     "医疗医药"),
    ("CAH",   "Cardinal Health",              "医疗医药"),
    ("IQV",   "IQVIA Holdings",               "医疗医药"),
    ("GEHC",  "GE HealthCare",                "医疗医药"),
    ("DXCM",  "DexCom",                       "医疗医药"),
    ("IDXX",  "IDEXX Laboratories",           "医疗医药"),
    ("A",     "Agilent Technologies",         "医疗医药"),
    ("PODD",  "Insulet",                      "医疗医药"),
    ("MTD",   "Mettler-Toledo",               "医疗医药"),
    ("RVMD",  "Revolution Medicines",         "医疗医药"),
    ("ARWR",  "Arrowhead Pharma",             "医疗医药"),
    ("NUVL",  "Nuvalent",                     "医疗医药"),
    ("TMDX",  "TransMedics Group",            "医疗医药"),
    ("ITCI",  "Intra-Cellular Therapies",     "医疗医药"),
    ("RCKT",  "Rocket Pharma",                "医疗医药"),
    ("ACAD",  "ACADIA Pharma",                "医疗医药"),
    ("FOLD",  "Amicus Therapeutics",          "医疗医药"),
    ("HALO",  "Halozyme Therapeutics",        "医疗医药"),
    ("RARE",  "Ultragenyx Pharma",            "医疗医药"),
    ("KRYS",  "Krystal Biotech",              "医疗医药"),
    ("CRSP",  "CRISPR Therapeutics",          "医疗医药"),
    ("BEAM",  "Beam Therapeutics",            "医疗医药"),
    ("NTLA",  "Intellia Therapeutics",        "医疗医药"),
    ("VERV",  "Verve Therapeutics",           "医疗医药"),
    ("PCVX",  "Vaxcyte",                      "医疗医药"),
    ("ILMN",  "Illumina",                     "医疗医药"),

    # ── 消费 ──────────────────────────────────────────────────────────────
    ("AMZN",  "Amazon",                       "消费"),
    ("TSLA",  "Tesla",                        "消费"),
    ("HD",    "Home Depot",                   "消费"),
    ("MCD",   "McDonald's",                   "消费"),
    ("NKE",   "Nike",                         "消费"),
    ("LOW",   "Lowe's",                       "消费"),
    ("BKNG",  "Booking Holdings",             "消费"),
    ("TJX",   "TJX Companies",               "消费"),
    ("SBUX",  "Starbucks",                    "消费"),
    ("ABNB",  "Airbnb",                       "消费"),
    ("CMG",   "Chipotle Mexican Grill",       "消费"),
    ("F",     "Ford Motor",                   "消费"),
    ("GM",    "General Motors",               "消费"),
    ("EBAY",  "eBay",                         "消费"),
    ("ETSY",  "Etsy",                         "消费"),
    ("RCL",   "Royal Caribbean",              "消费"),
    ("CCL",   "Carnival Corp",                "消费"),
    ("MAR",   "Marriott International",       "消费"),
    ("HLT",   "Hilton Worldwide",             "消费"),
    ("YUM",   "Yum Brands",                   "消费"),
    ("DRI",   "Darden Restaurants",           "消费"),
    ("EXPE",  "Expedia Group",                "消费"),
    ("ORLY",  "O'Reilly Automotive",          "消费"),
    ("AZO",   "AutoZone",                     "消费"),
    ("BBY",   "Best Buy",                     "消费"),
    ("ROST",  "Ross Stores",                  "消费"),
    ("ULTA",  "Ulta Beauty",                  "消费"),
    ("DHI",   "D.R. Horton",                  "消费"),
    ("LEN",   "Lennar",                       "消费"),
    ("PHM",   "PulteGroup",                   "消费"),
    ("DASH",  "DoorDash",                     "消费"),
    ("MELI",  "MercadoLibre",                 "消费"),
    ("CPNG",  "Coupang",                      "消费"),
    ("CELH",  "Celsius Holdings",             "消费"),
    ("BROS",  "Dutch Bros",                   "消费"),
    ("WING",  "Wingstop",                     "消费"),
    ("CAVA",  "CAVA Group",                   "消费"),
    ("BOOT",  "Boot Barn",                    "消费"),
    ("YETI",  "YETI Holdings",                "消费"),
    ("LULU",  "Lululemon",                    "消费"),
    ("WMT",   "Walmart",                      "消费"),
    ("PG",    "Procter & Gamble",             "消费"),
    ("KO",    "Coca-Cola",                    "消费"),
    ("PEP",   "PepsiCo",                      "消费"),
    ("COST",  "Costco",                       "消费"),
    ("PM",    "Philip Morris",                "消费"),
    ("MO",    "Altria Group",                 "消费"),
    ("MDLZ",  "Mondelez International",       "消费"),
    ("CL",    "Colgate-Palmolive",            "消费"),
    ("KMB",   "Kimberly-Clark",               "消费"),
    ("GIS",   "General Mills",                "消费"),
    ("HSY",   "Hershey",                      "消费"),
    ("STZ",   "Constellation Brands",         "消费"),
    ("ADM",   "Archer-Daniels-Midland",       "消费"),
    ("SYY",   "Sysco",                        "消费"),
    ("KR",    "Kroger",                       "消费"),
    ("TGT",   "Target",                       "消费"),
    ("MNST",  "Monster Beverage",             "消费"),
    ("KDP",   "Keurig Dr Pepper",             "消费"),
    ("DLTR",  "Dollar Tree",                  "消费"),
    ("NFLX",  "Netflix",                      "消费"),

    # ── 工业 ──────────────────────────────────────────────────────────────
    ("GE",    "GE Aerospace",                 "工业"),
    ("HON",   "Honeywell",                    "工业"),
    ("CAT",   "Caterpillar",                  "工业"),
    ("UPS",   "United Parcel Service",        "工业"),
    ("DE",    "Deere & Company",              "工业"),
    ("ETN",   "Eaton",                        "工业"),
    ("EMR",   "Emerson Electric",             "工业"),
    ("ROK",   "Rockwell Automation",          "工业"),
    ("AME",   "AMETEK",                       "工业"),
    ("PH",    "Parker-Hannifin",              "工业"),
    ("ITW",   "Illinois Tool Works",          "工业"),
    ("DOV",   "Dover",                        "工业"),
    ("XYL",   "Xylem",                        "工业"),
    ("FTV",   "Fortive",                      "工业"),
    ("ROP",   "Roper Technologies",           "工业"),
    ("IR",    "Ingersoll Rand",               "工业"),
    ("TT",    "Trane Technologies",           "工业"),
    ("CARR",  "Carrier Global",               "工业"),
    ("OTIS",  "Otis Worldwide",               "工业"),
    ("FDX",   "FedEx",                        "工业"),
    ("CSX",   "CSX",                          "工业"),
    ("UNP",   "Union Pacific",                "工业"),
    ("NSC",   "Norfolk Southern",             "工业"),
    ("WAB",   "Wabtec",                       "工业"),
    ("GWW",   "WW Grainger",                  "工业"),
    ("FAST",  "Fastenal",                     "工业"),
    ("SNA",   "Snap-on",                      "工业"),
    ("SWK",   "Stanley Black & Decker",       "工业"),
    ("CTAS",  "Cintas",                       "工业"),
    ("VRSK",  "Verisk Analytics",             "工业"),
    ("BR",    "Broadridge Financial",         "工业"),
    ("ADP",   "ADP",                          "工业"),
    ("PCAR",  "PACCAR",                       "工业"),
    ("PAYX",  "Paychex",                      "工业"),
    ("CPRT",  "Copart",                       "工业"),
    ("ODFL",  "Old Dominion Freight",         "工业"),
    ("DAL",   "Delta Air Lines",              "工业"),
    ("UAL",   "United Airlines",              "工业"),
    ("AAL",   "American Airlines",            "工业"),
    ("LUV",   "Southwest Airlines",           "工业"),
    ("HURN",  "Huron Consulting",             "工业"),
    ("POWL",  "Powell Industries",            "工业"),

    # ── 国防航天 ──────────────────────────────────────────────────────────
    ("RTX",   "RTX Corp",                     "国防航天"),
    ("BA",    "Boeing",                       "国防航天"),
    ("LMT",   "Lockheed Martin",              "国防航天"),
    ("NOC",   "Northrop Grumman",             "国防航天"),
    ("GD",    "General Dynamics",             "国防航天"),
    ("LHX",   "L3Harris Technologies",        "国防航天"),
    ("TDG",   "TransDigm Group",              "国防航天"),
    ("HWM",   "Howmet Aerospace",             "国防航天"),
    ("KTOS",  "Kratos Defense",               "国防航天"),
    ("RKLB",  "Rocket Lab",                   "国防航天"),
    ("ACHR",  "Archer Aviation",              "国防航天"),
    ("JOBY",  "Joby Aviation",                "国防航天"),
    ("LUNR",  "Intuitive Machines",           "国防航天"),
    ("ASTS",  "AST SpaceMobile",              "国防航天"),
    ("RDW",   "Redwire",                      "国防航天"),
    ("SATL",  "Satellogic",                   "国防航天"),
    ("SPIR",  "Spire Global",                 "国防航天"),
    ("BWXT",  "BWX Technologies",             "国防航天"),
    ("ATRO",  "Astronics",                    "国防航天"),

    # ── 能源 ──────────────────────────────────────────────────────────────
    ("XOM",   "ExxonMobil",                   "能源"),
    ("CVX",   "Chevron",                      "能源"),
    ("COP",   "ConocoPhillips",               "能源"),
    ("EOG",   "EOG Resources",                "能源"),
    ("SLB",   "SLB",                          "能源"),
    ("MPC",   "Marathon Petroleum",           "能源"),
    ("PSX",   "Phillips 66",                  "能源"),
    ("VLO",   "Valero Energy",                "能源"),
    ("OXY",   "Occidental Petroleum",         "能源"),
    ("HES",   "Hess",                         "能源"),
    ("DVN",   "Devon Energy",                 "能源"),
    ("FANG",  "Diamondback Energy",           "能源"),
    ("APA",   "APA Corp",                     "能源"),
    ("HAL",   "Halliburton",                  "能源"),
    ("BKR",   "Baker Hughes",                 "能源"),
    ("KMI",   "Kinder Morgan",                "能源"),
    ("WMB",   "Williams Companies",           "能源"),
    ("OKE",   "ONEOK",                        "能源"),
    ("TRGP",  "Targa Resources",              "能源"),
    ("CIVI",  "Civitas Resources",            "能源"),
    ("VTLE",  "Vital Energy",                 "能源"),

    # ── 新能源 ────────────────────────────────────────────────────────────
    ("FSLR",  "First Solar",                  "新能源"),
    ("ENPH",  "Enphase Energy",               "新能源"),
    ("NOVA",  "Sunnova Energy",               "新能源"),
    ("RUN",   "Sunrun",                       "新能源"),
    ("ARRY",  "Array Technologies",           "新能源"),
    ("SHLS",  "Shoals Technologies",          "新能源"),
    ("STEM",  "Stem Inc",                     "新能源"),
    ("FLNC",  "Fluence Energy",               "新能源"),
    ("CEG",   "Constellation Energy",         "新能源"),

    # ── 原材料 ────────────────────────────────────────────────────────────
    ("LIN",   "Linde",                        "原材料"),
    ("APD",   "Air Products",                 "原材料"),
    ("SHW",   "Sherwin-Williams",             "原材料"),
    ("ECL",   "Ecolab",                       "原材料"),
    ("DD",    "DuPont",                       "原材料"),
    ("DOW",   "Dow",                          "原材料"),
    ("LYB",   "LyondellBasell",               "原材料"),
    ("PPG",   "PPG Industries",               "原材料"),
    ("NUE",   "Nucor",                        "原材料"),
    ("STLD",  "Steel Dynamics",               "原材料"),
    ("VMC",   "Vulcan Materials",             "原材料"),
    ("MLM",   "Martin Marietta Materials",    "原材料"),
    ("CF",    "CF Industries",                "原材料"),
    ("MOS",   "Mosaic",                       "原材料"),
    ("ALB",   "Albemarle",                    "原材料"),
    ("IFF",   "International Flavors",        "原材料"),
    ("FCX",   "Freeport-McMoRan",             "原材料"),
    ("MP",    "MP Materials",                 "原材料"),
    ("UUUU",  "Energy Fuels",                 "原材料"),
    ("PLAB",  "Photronics",                   "原材料"),

    # ── 贵金属 ────────────────────────────────────────────────────────────
    ("NEM",   "Newmont",                      "贵金属"),
    ("AEM",   "Agnico Eagle Mines",           "贵金属"),
    ("WPM",   "Wheaton Precious Metals",      "贵金属"),
    ("FNV",   "Franco-Nevada",                "贵金属"),
    ("GOLD",  "Barrick Gold",                 "贵金属"),
    ("KGC",   "Kinross Gold",                 "贵金属"),
    ("HL",    "Hecla Mining",                 "贵金属"),
    ("PAAS",  "Pan American Silver",          "贵金属"),

    # ── 大宗商品 ──────────────────────────────────────────────────────────
    ("ADM",   "Archer-Daniels-Midland",       "大宗商品"),
    ("BG",    "Bunge Global",                 "大宗商品"),
    ("CTVA",  "Corteva",                      "大宗商品"),
    ("NTR",   "Nutrien",                      "大宗商品"),
    ("MOS",   "Mosaic",                       "大宗商品"),

    # ── 公用事业 ──────────────────────────────────────────────────────────
    ("NEE",   "NextEra Energy",               "公用事业"),
    ("SO",    "Southern Company",             "公用事业"),
    ("DUK",   "Duke Energy",                  "公用事业"),
    ("AEP",   "American Electric Power",      "公用事业"),
    ("D",     "Dominion Energy",              "公用事业"),
    ("SRE",   "Sempra",                       "公用事业"),
    ("EXC",   "Exelon",                       "公用事业"),
    ("XEL",   "Xcel Energy",                  "公用事业"),
    ("ED",    "Consolidated Edison",          "公用事业"),
    ("WEC",   "WEC Energy Group",             "公用事业"),
    ("ETR",   "Entergy",                      "公用事业"),
    ("EIX",   "Edison International",         "公用事业"),
    ("PPL",   "PPL Corp",                     "公用事业"),
    ("AES",   "AES Corp",                     "公用事业"),
    ("CMS",   "CMS Energy",                   "公用事业"),
    ("T",     "AT&T",                         "公用事业"),
    ("VZ",    "Verizon",                      "公用事业"),
    ("TMUS",  "T-Mobile",                     "公用事业"),
    ("CHTR",  "Charter Communications",       "公用事业"),
    ("CMCSA", "Comcast",                      "公用事业"),

    # ── 房地产 ────────────────────────────────────────────────────────────
    ("PLD",   "Prologis",                     "房地产"),
    ("AMT",   "American Tower",               "房地产"),
    ("EQIX",  "Equinix",                      "房地产"),
    ("CCI",   "Crown Castle",                 "房地产"),
    ("SPG",   "Simon Property Group",         "房地产"),
    ("O",     "Realty Income",                "房地产"),
    ("DLR",   "Digital Realty",               "房地产"),
    ("PSA",   "Public Storage",               "房地产"),
    ("EXR",   "Extra Space Storage",          "房地产"),
    ("AVB",   "AvalonBay Communities",        "房地产"),
    ("EQR",   "Equity Residential",           "房地产"),
    ("ARE",   "Alexandria Real Estate",       "房地产"),
    ("WELL",  "Welltower",                    "房地产"),
    ("HST",   "Host Hotels & Resorts",        "房地产"),
    ("IRM",   "Iron Mountain",                "房地产"),
    ("SBAC",  "SBA Communications",           "房地产"),
    ("CSGP",  "CoStar Group",                 "房地产"),
]

# ─── 板块列表（与ETF趋势系统完全一致）────────────────────────────────────
SECTORS_US = sorted({sec for _, _, sec in STOCKS_US})

# ─── 查询函数 ──────────────────────────────────────────────────────────────
def get_stocks_by_sector(sector):
    """按板块筛选个股，返回 {symbol: {name, sector}}"""
    return {
        sym: {"name": name, "sector": sec}
        for sym, name, sec in STOCKS_US
        if sec == sector
    }

# ─── 统计（调试用）────────────────────────────────────────────────────────
if __name__ == "__main__":
    from collections import Counter
    sectors = Counter(sec for _, _, sec in STOCKS_US)
    print(f"总共: {len(STOCKS_US)}只")
    for sec, count in sorted(sectors.items(), key=lambda x: -x[1]):
        print(f"  {sec}: {count}只")
