#!/usr/bin/env python3
"""
美股个股清单 - 自维护版本
格式: ("代码", "公司名", "GICS板块")
直接加到列表即可，无需任何外部数据源
板块用GICS标准：Information Technology / Health Care / Financials /
               Consumer Discretionary / Consumer Staples / Industrials /
               Energy / Materials / Utilities / Real Estate /
               Communication Services
"""

STOCKS_US = [
    # ── Information Technology ─────────────────────────────────────────────
    ("AAPL",  "Apple",                        "Information Technology"),
    ("MSFT",  "Microsoft",                    "Information Technology"),
    ("NVDA",  "NVIDIA",                       "Information Technology"),
    ("AMD",   "Advanced Micro Devices",       "Information Technology"),
    ("AVGO",  "Broadcom",                     "Information Technology"),
    ("ORCL",  "Oracle",                       "Information Technology"),
    ("CRM",   "Salesforce",                   "Information Technology"),
    ("ACN",   "Accenture",                    "Information Technology"),
    ("CSCO",  "Cisco",                        "Information Technology"),
    ("IBM",   "IBM",                          "Information Technology"),
    ("INTC",  "Intel",                        "Information Technology"),
    ("QCOM",  "Qualcomm",                     "Information Technology"),
    ("TXN",   "Texas Instruments",            "Information Technology"),
    ("NOW",   "ServiceNow",                   "Information Technology"),
    ("INTU",  "Intuit",                       "Information Technology"),
    ("AMAT",  "Applied Materials",            "Information Technology"),
    ("LRCX",  "Lam Research",                 "Information Technology"),
    ("KLAC",  "KLA Corp",                     "Information Technology"),
    ("MRVL",  "Marvell Technology",           "Information Technology"),
    ("CDNS",  "Cadence Design Systems",       "Information Technology"),
    ("SNPS",  "Synopsys",                     "Information Technology"),
    ("ADSK",  "Autodesk",                     "Information Technology"),
    ("FTNT",  "Fortinet",                     "Information Technology"),
    ("CRWD",  "CrowdStrike",                  "Information Technology"),
    ("PANW",  "Palo Alto Networks",           "Information Technology"),
    ("MSI",   "Motorola Solutions",           "Information Technology"),
    ("APH",   "Amphenol",                     "Information Technology"),
    ("GLW",   "Corning",                      "Information Technology"),
    ("HPQ",   "HP Inc",                       "Information Technology"),
    ("HPE",   "Hewlett Packard Enterprise",   "Information Technology"),
    ("DELL",  "Dell Technologies",            "Information Technology"),
    ("NTAP",  "NetApp",                       "Information Technology"),
    ("ON",    "ON Semiconductor",             "Information Technology"),
    ("MPWR",  "Monolithic Power Systems",     "Information Technology"),
    ("TER",   "Teradyne",                     "Information Technology"),
    ("KEYS",  "Keysight Technologies",        "Information Technology"),
    ("TEL",   "TE Connectivity",              "Information Technology"),
    ("STX",   "Seagate Technology",           "Information Technology"),
    ("WDC",   "Western Digital",              "Information Technology"),
    ("FSLR",  "First Solar",                  "Information Technology"),
    ("ENPH",  "Enphase Energy",               "Information Technology"),
    ("ZBRA",  "Zebra Technologies",           "Information Technology"),
    ("PAYC",  "Paycom Software",              "Information Technology"),
    ("GDDY",  "GoDaddy",                      "Information Technology"),
    ("AKAM",  "Akamai Technologies",          "Information Technology"),
    ("CTSH",  "Cognizant Technology",         "Information Technology"),
    ("IT",    "Gartner",                      "Information Technology"),
    ("PLTR",  "Palantir",                     "Information Technology"),
    ("DDOG",  "Datadog",                      "Information Technology"),
    ("SNOW",  "Snowflake",                    "Information Technology"),
    ("ZS",    "Zscaler",                      "Information Technology"),
    ("TEAM",  "Atlassian",                    "Information Technology"),
    ("WDAY",  "Workday",                      "Information Technology"),
    ("OKTA",  "Okta",                         "Information Technology"),
    ("ARM",   "ARM Holdings",                 "Information Technology"),
    ("SMCI",  "Super Micro Computer",         "Information Technology"),
    ("NTNX",  "Nutanix",                      "Information Technology"),
    ("ANSS",  "ANSYS",                        "Information Technology"),
    ("PTC",   "PTC Inc",                      "Information Technology"),
    ("EPAM",  "EPAM Systems",                 "Information Technology"),
    ("GEN",   "Gen Digital",                  "Information Technology"),
    ("FFIV",  "F5 Inc",                       "Information Technology"),

    # ── Communication Services ─────────────────────────────────────────────
    ("GOOGL", "Alphabet Class A",             "Communication Services"),
    ("GOOG",  "Alphabet Class C",             "Communication Services"),
    ("META",  "Meta Platforms",               "Communication Services"),
    ("NFLX",  "Netflix",                      "Communication Services"),
    ("DIS",   "Walt Disney",                  "Communication Services"),
    ("CMCSA", "Comcast",                      "Communication Services"),
    ("T",     "AT&T",                         "Communication Services"),
    ("VZ",    "Verizon",                      "Communication Services"),
    ("TMUS",  "T-Mobile",                     "Communication Services"),
    ("CHTR",  "Charter Communications",       "Communication Services"),
    ("TTWO",  "Take-Two Interactive",         "Communication Services"),
    ("EA",    "Electronic Arts",              "Communication Services"),
    ("WBD",   "Warner Bros Discovery",        "Communication Services"),
    ("OMC",   "Omnicom Group",                "Communication Services"),
    ("IPG",   "Interpublic Group",            "Communication Services"),
    ("FOXA",  "Fox Corp Class A",             "Communication Services"),
    ("LYV",   "Live Nation Entertainment",    "Communication Services"),
    ("MTCH",  "Match Group",                  "Communication Services"),
    ("PINS",  "Pinterest",                    "Communication Services"),
    ("SNAP",  "Snap",                         "Communication Services"),
    ("RBLX",  "Roblox",                       "Communication Services"),

    # ── Consumer Discretionary ─────────────────────────────────────────────
    ("AMZN",  "Amazon",                       "Consumer Discretionary"),
    ("TSLA",  "Tesla",                        "Consumer Discretionary"),
    ("HD",    "Home Depot",                   "Consumer Discretionary"),
    ("MCD",   "McDonald's",                   "Consumer Discretionary"),
    ("NKE",   "Nike",                         "Consumer Discretionary"),
    ("LOW",   "Lowe's",                       "Consumer Discretionary"),
    ("BKNG",  "Booking Holdings",             "Consumer Discretionary"),
    ("TJX",   "TJX Companies",               "Consumer Discretionary"),
    ("SBUX",  "Starbucks",                    "Consumer Discretionary"),
    ("ABNB",  "Airbnb",                       "Consumer Discretionary"),
    ("CMG",   "Chipotle Mexican Grill",       "Consumer Discretionary"),
    ("F",     "Ford Motor",                   "Consumer Discretionary"),
    ("GM",    "General Motors",               "Consumer Discretionary"),
    ("EBAY",  "eBay",                         "Consumer Discretionary"),
    ("ETSY",  "Etsy",                         "Consumer Discretionary"),
    ("RCL",   "Royal Caribbean",              "Consumer Discretionary"),
    ("CCL",   "Carnival Corp",                "Consumer Discretionary"),
    ("MAR",   "Marriott International",       "Consumer Discretionary"),
    ("HLT",   "Hilton Worldwide",             "Consumer Discretionary"),
    ("YUM",   "Yum Brands",                   "Consumer Discretionary"),
    ("DRI",   "Darden Restaurants",           "Consumer Discretionary"),
    ("EXPE",  "Expedia Group",                "Consumer Discretionary"),
    ("ORLY",  "O'Reilly Automotive",          "Consumer Discretionary"),
    ("AZO",   "AutoZone",                     "Consumer Discretionary"),
    ("BBY",   "Best Buy",                     "Consumer Discretionary"),
    ("ROST",  "Ross Stores",                  "Consumer Discretionary"),
    ("ULTA",  "Ulta Beauty",                  "Consumer Discretionary"),
    ("DHI",   "D.R. Horton",                  "Consumer Discretionary"),
    ("LEN",   "Lennar",                       "Consumer Discretionary"),
    ("PHM",   "PulteGroup",                   "Consumer Discretionary"),
    ("DASH",  "DoorDash",                     "Consumer Discretionary"),
    ("MELI",  "MercadoLibre",                 "Consumer Discretionary"),
    ("CPNG",  "Coupang",                      "Consumer Discretionary"),

    # ── Consumer Staples ───────────────────────────────────────────────────
    ("WMT",   "Walmart",                      "Consumer Staples"),
    ("PG",    "Procter & Gamble",             "Consumer Staples"),
    ("KO",    "Coca-Cola",                    "Consumer Staples"),
    ("PEP",   "PepsiCo",                      "Consumer Staples"),
    ("COST",  "Costco",                       "Consumer Staples"),
    ("PM",    "Philip Morris",                "Consumer Staples"),
    ("MO",    "Altria Group",                 "Consumer Staples"),
    ("MDLZ",  "Mondelez International",       "Consumer Staples"),
    ("CL",    "Colgate-Palmolive",            "Consumer Staples"),
    ("KMB",   "Kimberly-Clark",               "Consumer Staples"),
    ("GIS",   "General Mills",                "Consumer Staples"),
    ("HSY",   "Hershey",                      "Consumer Staples"),
    ("STZ",   "Constellation Brands",         "Consumer Staples"),
    ("ADM",   "Archer-Daniels-Midland",       "Consumer Staples"),
    ("SYY",   "Sysco",                        "Consumer Staples"),
    ("KR",    "Kroger",                       "Consumer Staples"),
    ("TGT",   "Target",                       "Consumer Staples"),
    ("CVS",   "CVS Health",                   "Consumer Staples"),

    # ── Financials ─────────────────────────────────────────────────────────
    ("BRK-B", "Berkshire Hathaway",           "Financials"),
    ("JPM",   "JPMorgan Chase",               "Financials"),
    ("BAC",   "Bank of America",              "Financials"),
    ("WFC",   "Wells Fargo",                  "Financials"),
    ("GS",    "Goldman Sachs",                "Financials"),
    ("MS",    "Morgan Stanley",               "Financials"),
    ("C",     "Citigroup",                    "Financials"),
    ("BLK",   "BlackRock",                    "Financials"),
    ("SCHW",  "Charles Schwab",               "Financials"),
    ("AXP",   "American Express",             "Financials"),
    ("CB",    "Chubb",                        "Financials"),
    ("MMC",   "Marsh & McLennan",             "Financials"),
    ("PGR",   "Progressive",                  "Financials"),
    ("MET",   "MetLife",                      "Financials"),
    ("PRU",   "Prudential Financial",         "Financials"),
    ("AFL",   "Aflac",                        "Financials"),
    ("TRV",   "Travelers Companies",          "Financials"),
    ("AON",   "Aon",                          "Financials"),
    ("ICE",   "Intercontinental Exchange",    "Financials"),
    ("CME",   "CME Group",                    "Financials"),
    ("SPGI",  "S&P Global",                   "Financials"),
    ("MCO",   "Moody's",                      "Financials"),
    ("USB",   "US Bancorp",                   "Financials"),
    ("PNC",   "PNC Financial",                "Financials"),
    ("TFC",   "Truist Financial",             "Financials"),
    ("COF",   "Capital One",                  "Financials"),
    ("DFS",   "Discover Financial",           "Financials"),
    ("SYF",   "Synchrony Financial",          "Financials"),
    ("FITB",  "Fifth Third Bancorp",          "Financials"),
    ("RF",    "Regions Financial",            "Financials"),
    ("V",     "Visa",                         "Financials"),
    ("MA",    "Mastercard",                   "Financials"),
    ("PYPL",  "PayPal",                       "Financials"),
    ("FI",    "Fiserv",                       "Financials"),
    ("FIS",   "Fidelity National Info",       "Financials"),
    ("GPN",   "Global Payments",              "Financials"),
    ("COIN",  "Coinbase",                     "Financials"),
    ("MSCI",  "MSCI Inc",                     "Financials"),
    ("FDS",   "FactSet Research",             "Financials"),

    # ── Health Care ────────────────────────────────────────────────────────
    ("LLY",   "Eli Lilly",                    "Health Care"),
    ("UNH",   "UnitedHealth Group",           "Health Care"),
    ("JNJ",   "Johnson & Johnson",            "Health Care"),
    ("ABBV",  "AbbVie",                       "Health Care"),
    ("MRK",   "Merck",                        "Health Care"),
    ("PFE",   "Pfizer",                       "Health Care"),
    ("TMO",   "Thermo Fisher Scientific",     "Health Care"),
    ("ABT",   "Abbott Laboratories",          "Health Care"),
    ("DHR",   "Danaher",                      "Health Care"),
    ("BMY",   "Bristol-Myers Squibb",         "Health Care"),
    ("AMGN",  "Amgen",                        "Health Care"),
    ("GILD",  "Gilead Sciences",              "Health Care"),
    ("REGN",  "Regeneron Pharmaceuticals",    "Health Care"),
    ("VRTX",  "Vertex Pharmaceuticals",       "Health Care"),
    ("BIIB",  "Biogen",                       "Health Care"),
    ("MRNA",  "Moderna",                      "Health Care"),
    ("ISRG",  "Intuitive Surgical",           "Health Care"),
    ("SYK",   "Stryker",                      "Health Care"),
    ("BSX",   "Boston Scientific",            "Health Care"),
    ("MDT",   "Medtronic",                    "Health Care"),
    ("EW",    "Edwards Lifesciences",         "Health Care"),
    ("BDX",   "Becton Dickinson",             "Health Care"),
    ("HUM",   "Humana",                       "Health Care"),
    ("CI",    "Cigna",                        "Health Care"),
    ("CNC",   "Centene",                      "Health Care"),
    ("MCK",   "McKesson",                     "Health Care"),
    ("CAH",   "Cardinal Health",              "Health Care"),
    ("DGX",   "Quest Diagnostics",            "Health Care"),
    ("IQV",   "IQVIA Holdings",               "Health Care"),
    ("GEHC",  "GE HealthCare",                "Health Care"),
    ("DXCM",  "DexCom",                       "Health Care"),
    ("IDXX",  "IDEXX Laboratories",           "Health Care"),
    ("A",     "Agilent Technologies",         "Health Care"),
    ("PODD",  "Insulet",                      "Health Care"),
    ("MTD",   "Mettler-Toledo",               "Health Care"),

    # ── Industrials ────────────────────────────────────────────────────────
    ("GE",    "GE Aerospace",                 "Industrials"),
    ("RTX",   "RTX Corp",                     "Industrials"),
    ("HON",   "Honeywell",                    "Industrials"),
    ("CAT",   "Caterpillar",                  "Industrials"),
    ("UPS",   "United Parcel Service",        "Industrials"),
    ("DE",    "Deere & Company",              "Industrials"),
    ("BA",    "Boeing",                       "Industrials"),
    ("LMT",   "Lockheed Martin",              "Industrials"),
    ("NOC",   "Northrop Grumman",             "Industrials"),
    ("GD",    "General Dynamics",             "Industrials"),
    ("LHX",   "L3Harris Technologies",        "Industrials"),
    ("TDG",   "TransDigm Group",              "Industrials"),
    ("HWM",   "Howmet Aerospace",             "Industrials"),
    ("ETN",   "Eaton",                        "Industrials"),
    ("EMR",   "Emerson Electric",             "Industrials"),
    ("ROK",   "Rockwell Automation",          "Industrials"),
    ("AME",   "AMETEK",                       "Industrials"),
    ("PH",    "Parker-Hannifin",              "Industrials"),
    ("ITW",   "Illinois Tool Works",          "Industrials"),
    ("DOV",   "Dover",                        "Industrials"),
    ("XYL",   "Xylem",                        "Industrials"),
    ("FTV",   "Fortive",                      "Industrials"),
    ("ROP",   "Roper Technologies",           "Industrials"),
    ("IR",    "Ingersoll Rand",               "Industrials"),
    ("TT",    "Trane Technologies",           "Industrials"),
    ("CARR",  "Carrier Global",               "Industrials"),
    ("OTIS",  "Otis Worldwide",               "Industrials"),
    ("FDX",   "FedEx",                        "Industrials"),
    ("DAL",   "Delta Air Lines",              "Industrials"),
    ("UAL",   "United Airlines",              "Industrials"),
    ("AAL",   "American Airlines",            "Industrials"),
    ("LUV",   "Southwest Airlines",           "Industrials"),
    ("CSX",   "CSX",                          "Industrials"),
    ("UNP",   "Union Pacific",                "Industrials"),
    ("NSC",   "Norfolk Southern",             "Industrials"),
    ("WAB",   "Wabtec",                       "Industrials"),
    ("GWW",   "WW Grainger",                  "Industrials"),
    ("FAST",  "Fastenal",                     "Industrials"),
    ("SNA",   "Snap-on",                      "Industrials"),
    ("SWK",   "Stanley Black & Decker",       "Industrials"),
    ("CTAS",  "Cintas",                       "Industrials"),
    ("VRSK",  "Verisk Analytics",             "Industrials"),
    ("BR",    "Broadridge Financial",         "Industrials"),
    ("PAVE",  "Global X US Infrastructure",   "Industrials"),
    ("RKLB",  "Rocket Lab",                   "Industrials"),
    ("JOBY",  "Joby Aviation",                "Industrials"),
    ("ACHR",  "Archer Aviation",              "Industrials"),

    # ── Energy ─────────────────────────────────────────────────────────────
    ("XOM",   "ExxonMobil",                   "Energy"),
    ("CVX",   "Chevron",                      "Energy"),
    ("COP",   "ConocoPhillips",               "Energy"),
    ("EOG",   "EOG Resources",                "Energy"),
    ("SLB",   "SLB",                          "Energy"),
    ("MPC",   "Marathon Petroleum",           "Energy"),
    ("PSX",   "Phillips 66",                  "Energy"),
    ("VLO",   "Valero Energy",                "Energy"),
    ("OXY",   "Occidental Petroleum",         "Energy"),
    ("HES",   "Hess",                         "Energy"),
    ("DVN",   "Devon Energy",                 "Energy"),
    ("FANG",  "Diamondback Energy",           "Energy"),
    ("APA",   "APA Corp",                     "Energy"),
    ("HAL",   "Halliburton",                  "Energy"),
    ("BKR",   "Baker Hughes",                 "Energy"),
    ("KMI",   "Kinder Morgan",                "Energy"),
    ("WMB",   "Williams Companies",           "Energy"),
    ("OKE",   "ONEOK",                        "Energy"),
    ("TRGP",  "Targa Resources",              "Energy"),

    # ── Materials ──────────────────────────────────────────────────────────
    ("LIN",   "Linde",                        "Materials"),
    ("APD",   "Air Products",                 "Materials"),
    ("SHW",   "Sherwin-Williams",             "Materials"),
    ("ECL",   "Ecolab",                       "Materials"),
    ("DD",    "DuPont",                       "Materials"),
    ("DOW",   "Dow",                          "Materials"),
    ("LYB",   "LyondellBasell",               "Materials"),
    ("PPG",   "PPG Industries",               "Materials"),
    ("NEM",   "Newmont",                      "Materials"),
    ("FCX",   "Freeport-McMoRan",             "Materials"),
    ("NUE",   "Nucor",                        "Materials"),
    ("STLD",  "Steel Dynamics",               "Materials"),
    ("VMC",   "Vulcan Materials",             "Materials"),
    ("MLM",   "Martin Marietta Materials",    "Materials"),
    ("CF",    "CF Industries",                "Materials"),
    ("MOS",   "Mosaic",                       "Materials"),
    ("ALB",   "Albemarle",                    "Materials"),
    ("IFF",   "International Flavors",        "Materials"),

    # ── Utilities ──────────────────────────────────────────────────────────
    ("NEE",   "NextEra Energy",               "Utilities"),
    ("SO",    "Southern Company",             "Utilities"),
    ("DUK",   "Duke Energy",                  "Utilities"),
    ("AEP",   "American Electric Power",      "Utilities"),
    ("D",     "Dominion Energy",              "Utilities"),
    ("SRE",   "Sempra",                       "Utilities"),
    ("EXC",   "Exelon",                       "Utilities"),
    ("XEL",   "Xcel Energy",                  "Utilities"),
    ("ED",    "Consolidated Edison",          "Utilities"),
    ("WEC",   "WEC Energy Group",             "Utilities"),
    ("ES",    "Eversource Energy",            "Utilities"),
    ("ETR",   "Entergy",                      "Utilities"),
    ("FE",    "FirstEnergy",                  "Utilities"),
    ("EIX",   "Edison International",         "Utilities"),
    ("PPL",   "PPL Corp",                     "Utilities"),
    ("AES",   "AES Corp",                     "Utilities"),
    ("CMS",   "CMS Energy",                   "Utilities"),

    # ── Real Estate ────────────────────────────────────────────────────────
    ("PLD",   "Prologis",                     "Real Estate"),
    ("AMT",   "American Tower",               "Real Estate"),
    ("EQIX",  "Equinix",                      "Real Estate"),
    ("CCI",   "Crown Castle",                 "Real Estate"),
    ("SPG",   "Simon Property Group",         "Real Estate"),
    ("O",     "Realty Income",                "Real Estate"),
    ("DLR",   "Digital Realty",               "Real Estate"),
    ("PSA",   "Public Storage",               "Real Estate"),
    ("EXR",   "Extra Space Storage",          "Real Estate"),
    ("AVB",   "AvalonBay Communities",        "Real Estate"),
    ("EQR",   "Equity Residential",           "Real Estate"),
    ("ARE",   "Alexandria Real Estate",       "Real Estate"),
    ("WELL",  "Welltower",                    "Real Estate"),
    ("HST",   "Host Hotels & Resorts",        "Real Estate"),
    ("IRM",   "Iron Mountain",                "Real Estate"),
    ("SBAC",  "SBA Communications",           "Real Estate"),
]

# ─── ETF趋势系统板块 → GICS板块 映射 ──────────────────────────────────────
SECTOR_MAP = {
    "半导体":    ["Information Technology"],
    "科技":      ["Information Technology", "Communication Services"],
    "人工智能":  ["Information Technology", "Communication Services"],
    "云计算软件":["Information Technology", "Communication Services"],
    "金融":      ["Financials"],
    "医药医疗":  ["Health Care"],
    "能源":      ["Energy"],
    "新能源光伏":["Utilities", "Information Technology"],
    "消费":      ["Consumer Discretionary", "Consumer Staples"],
    "工业":      ["Industrials"],
    "原材料":    ["Materials"],
    "贵金属":    ["Materials"],
    "房地产":    ["Real Estate"],
    "公用事业":  ["Utilities"],
    "国防航天":  ["Industrials"],
    "大宗商品":  ["Materials", "Energy"],
    "债券":      [],
    "恐慌":      [],
    "杠杆":      [],
}

# ─── 查询函数 ──────────────────────────────────────────────────────────────
def get_stocks_by_gics(sector_gics):
    """按GICS板块筛选个股，返回 {symbol: {name, sector}}"""
    return {
        sym: {"name": name, "sector": sec}
        for sym, name, sec in STOCKS_US
        if sec == sector_gics
    }

def get_stocks_by_etf_sector(etf_sector):
    """按ETF趋势系统板块名获取对应个股"""
    gics_list = SECTOR_MAP.get(etf_sector, [])
    result = {}
    for gics in gics_list:
        result.update(get_stocks_by_gics(gics))
    return result

# ─── 统计（调试用）────────────────────────────────────────────────────────
if __name__ == "__main__":
    from collections import Counter
    sectors = Counter(sec for _, _, sec in STOCKS_US)
    print(f"总共: {len(STOCKS_US)}只")
    for sec, count in sorted(sectors.items(), key=lambda x: -x[1]):
        print(f"  {sec}: {count}只")
